url: https://fourtink.github.io
baseurl:

# Site settings
title: Fourtink Technology
email: contato@fourtink.com.br
description: "Fourtink Technology"


# Team names, titles and social links
people:
- name: Alan Soares
  pic: 1
  position: CEO and Founder
  social:
    - title: twitter
      url: https://twitter.com/alan_ssoares
    - title: facebook
      url: https://www.facebook.com/alanssoaress
    - title: google-plus
      url: https://plus.google.com/u/0/113371852609725526957
    - title: linkedin
      url: https://www.linkedin.com/in/alanssoares/
    - title: github
      url: https://github.com/alanssoares

- name: Rosane Monte
  pic: 2
  position: Lead Marketer
  social:
    - title: facebook
      url: https://www.facebook.com/viscondessa
    - title: linkedin
      url: https://www.linkedin.com/in/rosane-monte-b8b07b6a/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company-beta/16176415/

# Postal address (add as many lines as necessary)
address:
  - line: Salvador Shopping Business - Alameda Salvador, 1057, sala 912 - Caminho das Arvore
  - line: Brazil, Salvador - BA, 41820-790

# Build settings
markdown: kramdown
permalink: pretty
